### ISSUE TITLE
Support the --join option

### ISSUE THREAD

**Issue by sethlivingston** [gulp-community/gulp-coffee#60]
This was touched on in #14, but here is the problem: 

**coffee(join:true)** is not the same as **coffee() + concat()**

The latter will have extra cruft because each input file will be wrapped with the function safety wrapper.

Here's the code that doesn't work:

```
gulp.task 'concat', ->
  gulp.src myFilesInOrder, baseDir: myBaseDir
  .pipe coffee
    join: true
  .on 'error', gutil.log
  .pipe gulp.dest myDestFile
```

**Comment by PawelDecowski** [comment]
Any update on this?

**Comment by contra** [comment]
I'll take a PR for this if anyone wants to submit one, shouldn't be difficult

**Comment by GeoffreyBooth** [comment]
FWIW, the `--join` option in CoffeeScript has been deprecated for years (since before 2.0.0) and might disappear at any time. More robust tools like Browserify are encouraged instead.

**Comment by contra** [comment]
If join is deprecated then we won't add support for it.

**Comment by GeoffreyBooth** [comment]
> Also, isn’t `src -> concat -> coffee` the same thing?

It is, since you’re concatenating the CoffeeScript source _before_ compiling. But you’re still subject to whatever order `concat` uses to concatenate the files. You need to be careful not to refer to a variable before it’s been declared, which will depend on things like the alphabetical order of your filenames. This is why a tool with proper module support is beneficial.
